services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-server-fabric
    restart: unless-stopped
    # bypasses Docker NAT
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - ./minecraft-data:/data
      - ./mods:/data/mods

    deploy:
      resources:
        limits:
          memory: 4G

    environment:
      EULA: "TRUE"
      VERSION: "1.21.10"
      TYPE: "FABRIC"
      DIFFICULTY: "normal"
      ONLINE_MODE: "FALSE"
      ENFORCE_SECURE_PROFILE: "FALSE"

      MEMORY: "3G"
      USE_AIKAR_FLAGS: "true"

      # Bandwidth Cap
      VIEW_DISTANCE: "14"
      SIMULATION_DISTANCE: "9"
      NETWORK_COMPRESSION_THRESHOLD: "512"
